# Generated by Django 5.1.2 on 2024-11-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('matricula', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
