# Generated by Django 5.1.2 on 2025-01-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0002_titulacion_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulacion',
            name='carrera',
            field=models.IntegerField(choices=[('INGENIERÍA BIOQUÍMICA', 'INGENIERÍA BIOQUÍMICA'), ('INGENIERÍA CIVIL', 'INGENIERÍA CIVIL')], default='INGENIERÍA BIOQUÍMICA'),
        ),
    ]
