# Generated by Django 5.1.2 on 2025-01-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0003_alter_titulacion_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulacion',
            name='carrera',
            field=models.IntegerField(choices=[(0, 'INGENIERÍA BIOQUÍMICA'), (1, 'INGENIERÍA CIVIL'), (2, 'INGENIERÍA CIVIL')]),
        ),
    ]
