# Generated by Django 5.1.2 on 2025-03-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0005_alter_titulacion_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulacion',
            name='discapacidad',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=100),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=100),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='lugar',
            field=models.CharField(choices=[('Acayucan', 'Acayucan'), ('Oluta', 'Oluta'), ('Jaltipan', 'Jaltipan'), ('Texistepec', 'Texistepec'), ('Cosoleacaque', 'Cosoleacaque'), ('Hueyapan', 'Hueyapan'), ('Covarrubias', 'Covarrubias'), ('Otro', 'Otro')], default='Acayucan', max_length=100),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='modalidad',
            field=models.CharField(choices=[('Escolarizado', 'Escolarizado'), ('Sabatino', 'Sabatino'), ('Dominical', 'Dominical'), ('Extensión Hueyapan', 'Extensión Hueyapan'), ('Extensión Uxpanapan', 'Extensión Uxpanapan')], default='Escolarizado', max_length=100),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='titulacion_tipo',
            field=models.CharField(choices=[('Residencia profesional', 'Residencia profesional'), ('Tesis', 'Tesis'), ('Otro', 'Otro')], default='Residencia profesional', max_length=25),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='carrera',
            field=models.CharField(choices=[('INGENIERÍA BIOQUÍMICA', 'INGENIERÍA BIOQUÍMICA'), ('INGENIERÍA CIVIL', 'INGENIERÍA CIVIL'), ('INGENIERÍA ELECTROMECÁNICA', 'INGENIERÍA ELECTROMECÁNICA'), ('GESTIÓN EMPRESARIAL', 'GESTIÓN EMPRESARIAL'), ('INGENIERÍA DE SISTEMAS COMPUTACIONALES', 'INGENIERÍA DE SISTEMAS COMPUTACIONALES'), ('INGENIERÍA INDUSTRIAL', 'INGENIERÍA INDUSTRIAL'), ('INGENIERÍA INFORMÁTICA', 'INGENIERÍA INFORMÁTICA'), ('INGENIERÍA MECATRÓNICA', 'INGENIERÍA MECATRÓNICA'), ('INGENIERÍA QUÍMICA', 'INGENIERÍA QUÍMICA'), ('LICENCIATURA EN INFORMÁTICA', 'LICENCIATURA EN INFORMÁTICA')], default='INGENIERÍA BIOQUÍMICA', max_length=100),
        ),
    ]
