# Generated by Django 5.1.2 on 2025-03-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0006_titulacion_discapacidad_titulacion_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulacion',
            name='apellido_materno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='titulo_proyecto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
