# Generated by Django 5.1.2 on 2025-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0007_titulacion_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulacion',
            name='archivo',
            field=models.FileField(default='titulacion/default.pdf', upload_to='Titulacion'),
        ),
    ]
