# Generated by Django 5.1.2 on 2025-03-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0008_titulacion_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProfesor', models.CharField(max_length=100)),
                ('cedulaProfesor', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='archivo',
            field=models.FileField(upload_to='archivo'),
        ),
    ]
