# Generated by Django 5.1.2 on 2025-03-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0009_profesor_alter_titulacion_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='apellidoMaterno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellidoPaterno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='sigla',
            field=models.CharField(default='', max_length=10),
        ),
    ]
