# Generated by Django 5.1.2 on 2025-04-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0011_titulacion_nombre_del_asesor_titulacion_promedio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulacion',
            old_name='titulo_proyecto',
            new_name='nombre_del_proyecto',
        ),
        migrations.RenameField(
            model_name='titulacion',
            old_name='titulacion_tipo',
            new_name='opcion_de_titulacion',
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='carrera',
            field=models.CharField(choices=[('INGENIERÍA BIOQUÍMICA', 'INGENIERÍA BIOQUÍMICA'), ('INGENIERÍA CIVIL', 'INGENIERÍA CIVIL'), ('INGENIERÍA ELECTROMECÁNICA', 'INGENIERÍA ELECTROMECÁNICA'), ('INGENIERÍA EN GESTIÓN EMPRESARIAL', 'INGENIERÍA EN GESTIÓN EMPRESARIAL'), ('INGENIERÍA DE SISTEMAS COMPUTACIONALES', 'INGENIERÍA DE SISTEMAS COMPUTACIONALES'), ('INGENIERÍA INDUSTRIAL', 'INGENIERÍA INDUSTRIAL'), ('INGENIERÍA INFORMÁTICA', 'INGENIERÍA INFORMÁTICA'), ('INGENIERÍA MECATRÓNICA', 'INGENIERÍA MECATRÓNICA'), ('INGENIERÍA QUÍMICA', 'INGENIERÍA QUÍMICA'), ('LICENCIATURA EN INFORMÁTICA', 'LICENCIATURA EN INFORMÁTICA')], default='INGENIERÍA BIOQUÍMICA', max_length=100),
        ),
    ]
