# Generated by Django 5.1.2 on 2025-04-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0012_rename_titulo_proyecto_titulacion_nombre_del_proyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulacion',
            old_name='archivo',
            new_name='Adjunta_tu_proyecto_final_PDF',
        ),
    ]
