# Generated by Django 5.1.2 on 2025-04-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0013_rename_archivo_titulacion_adjunta_tu_proyecto_final_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulacion',
            old_name='Adjunta_tu_proyecto_final_PDF',
            new_name='archivo',
        ),
    ]
