# Generated by Django 5.1.2 on 2025-05-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0015_titulacion_nombre_del_revisor_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='nombre_del_proyecto',
            field=models.CharField(default='', max_length=205),
        ),
    ]
