# Generated by Django 5.1.2 on 2025-05-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0016_titulacion_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulacion',
            name='dialecto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuál dialecto?'),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='habla_dialecto',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Sí')], default=False, verbose_name='¿Habla algún dialecto?'),
        ),
    ]
