# Generated by Django 5.1.2 on 2025-05-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0017_titulacion_dialecto_titulacion_habla_dialecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulacion',
            name='habla_dialecto',
        ),
    ]
