# Generated by Django 5.1.2 on 2025-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0018_remove_titulacion_habla_dialecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='sigla',
            field=models.CharField(choices=[('MTI.', 'Maestría en Tecnologías de la Información'), ('MDIS.', 'Maestría en Diseño'), ('ING.', 'Ingeniero'), ('LIC.', 'Licenciado'), ('DR.', 'Doctor')], default='MTI', max_length=50),
        ),
    ]
