# Generated by Django 5.1.2 on 2025-05-25 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0019_alter_profesor_sigla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulacion',
            name='nombre_del_asesor',
        ),
        migrations.RemoveField(
            model_name='titulacion',
            name='nombre_del_revisor_1',
        ),
        migrations.RemoveField(
            model_name='titulacion',
            name='nombre_del_revisor_2',
        ),
        migrations.AddField(
            model_name='titulacion',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asesorados', to='Titulacion.profesor', verbose_name='Asesor'),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='revisor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_1', to='Titulacion.profesor', verbose_name='Revisor 1'),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='revisor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_2', to='Titulacion.profesor', verbose_name='Revisor 2'),
        ),
    ]
