# Generated by Django 5.1.2 on 2025-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0020_remove_titulacion_nombre_del_asesor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aprobado', models.CharField(max_length=100)),
            ],
        ),
    ]
