# Generated by Django 5.1.2 on 2025-06-05 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0022_remove_acta_aprobado_acta_anio_firma_acta_dia_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='anio_examen',
            field=models.CharField(blank=True, default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='anio_firmma',
            field=models.CharField(blank=True, default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='dia_examen',
            field=models.CharField(blank=True, default='1', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='dia_firmma',
            field=models.CharField(blank=True, default='1', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='dictamen',
            field=models.CharField(blank=True, default='Aprobado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='hora_fin',
            field=models.CharField(blank=True, default='13:00', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='hora_inicio',
            field=models.CharField(blank=True, default='12:00', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='mes_examen',
            field=models.CharField(blank=True, default='enero', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='mes_firma_final',
            field=models.CharField(blank=True, default='enero', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='nombre_director',
            field=models.CharField(blank=True, default='DR. Ricardo Ávila García', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='titulacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='Titulacion.titulacion'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='anio_firma',
            field=models.CharField(blank=True, default='2025', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='dia_firma',
            field=models.CharField(blank=True, default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='foja',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='libro',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='mes_firma',
            field=models.CharField(blank=True, default='enero', max_length=15, null=True),
        ),
    ]
