# Generated by Django 5.1.2 on 2025-06-11 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0023_acta_anio_examen_acta_anio_firmma_acta_dia_examen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={'verbose_name': 'Acta de Titulación', 'verbose_name_plural': 'Actas de Titulación'},
        ),
        migrations.AddField(
            model_name='profesor',
            name='email_prof',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono_prof',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nombre_director',
            field=models.CharField(blank=True, default='DR. Ricardo Ávila García.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='titulacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='Titulacion.titulacion'),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='modalidad',
            field=models.CharField(choices=[('Escolarizado', 'Escolarizado'), ('Sabatino', 'Sabatino'), ('Dominical', 'Dominical'), ('Extensión Hueyapan', 'Extensión Hueyapan'), ('Extensión Uxpanapan', 'Extensión Uxpanapan'), ('En Línea', 'En Linea')], default='Escolarizado', max_length=100),
        ),
    ]
