# Generated by Django 5.1.2 on 2025-06-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0024_alter_acta_options_profesor_email_prof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulacion',
            name='periodo_escolar',
            field=models.CharField(default='06/2025', help_text='Formato: MM/AAAA (ej. 06/2025)', max_length=20, verbose_name='Período Escolar'),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='matricula',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
