# Generated by Django 5.1.2 on 2025-06-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0025_titulacion_periodo_escolar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulacion',
            name='periodo_escolar',
        ),
        migrations.AddField(
            model_name='titulacion',
            name='periodo_escolar_Final',
            field=models.CharField(default='AGOSTO/2025', help_text='Formato: MES/AÑO (ej. DICIEMBRE-2025 /)', max_length=20, verbose_name='Período Escolar '),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='periodo_escolar_Inicio',
            field=models.CharField(default='AGOSTO/2022', help_text='Formato: MES/AÑO (ej. AGOSTO-2022 /)', max_length=20, verbose_name='Período Escolar '),
        ),
    ]
