# Generated by Django 5.1.2 on 2025-06-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0027_alter_titulacion_periodo_escolar_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='DR.', max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='apellido_materno',
            field=models.CharField(default='', help_text='<span style="color: red;">Escrito en Mayúsculas</span>', max_length=100),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='apellido_paterno',
            field=models.CharField(default='', help_text='<span style="color: red;">Escrito en Mayúsculas</span>', max_length=100),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='archivo',
            field=models.FileField(help_text='<span style="color: red; ">Adjunta tu proyecto final en formato PDF (el archivo debe pesar máximo 10MB)</span>', upload_to='archivo'),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='nombre',
            field=models.CharField(help_text='<span style="color: red;">Escrito en Mayúsculas</span>', max_length=100),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='nombre_del_proyecto',
            field=models.CharField(default='', help_text='<span style="color: red; ">Debe respetar el uso de minúsculas y mayúsculas según corresponda</span>', max_length=205),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='periodo_escolar_Final',
            field=models.CharField(default='DICIEMBRE/2025', help_text='<span style="color: red; ">Formato: MES/AÑO (ej. DICIEMBRE-2025) (100 CREDITOS ACOMULADOS) </span>', max_length=20),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='periodo_escolar_Inicio',
            field=models.CharField(default='AGOSTO/2022', help_text='<span style="color: red; ">Formato: MES/AÑO (ej. AGOSTO-2022)</span>', max_length=20),
        ),
    ]
