# Generated by Django 5.1.2 on 2025-06-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0028_director_alter_titulacion_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulacion',
            name='opcion_de_titulacion',
            field=models.CharField(choices=[('Residencia Profesional', 'Residencia Profesional'), ('Proyecto de Investigación y/o Desarrollo Tecnológico', 'Proyecto de Investigación y/o Desarrollo Tecnológico'), ('Proyecto Integrador', 'Proyecto Integrador'), ('Proyecto Productivo', 'Proyecto Productivo'), ('Proyecto de Innovación Tecnológica', 'Proyecto de Innovación Tecnológica'), ('Proyecto de Emprededurismo', 'Proyecto de Emprededurismo'), ('Estancia', 'Estancia'), ('Tesis o Tesina', 'Tesis o Tesina'), ('Examen General de Egreso de Licenciatura (EGEL) del Centro Nacional de Evaluación para la Educación Superior, A.C(CENEVAL)', 'Examen General de Egreso de Licenciatura (EGEL) del Centro Nacional de Evaluación para la Educación Superior, A.C(CENEVAL)')], default='Residencia Profesional', max_length=150),
        ),
    ]
