# Generated by Django 5.1.2 on 2025-06-27 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0029_alter_titulacion_opcion_de_titulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='telefono_prof',
            field=models.CharField(blank=True, help_text='Debe contener exactamente 10 dígitos', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='telefono',
            field=models.CharField(blank=True, help_text='Debe contener exactamente 10 dígitos', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
