from django.db import models # type: ignore

# Create your models here.


class Titulacion(models.Model):
    correo = models.EmailField(max_length = 254) 
    matricula = models.CharField(max_length=8) 
    nombre = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100, default="")
    apellido_materno = models.CharField(max_length=100, default="")
    edad = models.IntegerField(default=0)
    promedio = models.IntegerField(default=0)
    nombre_del_proyecto = models.CharField(max_length=205, default="")
    archivo = models.FileField(upload_to='archivo')
    telefono = models.CharField(max_length=10, blank=True, null=True)
    dialecto = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name="¿Cuál dialecto?"
    )
    carrera = models.CharField(max_length=100, choices=[
        ('INGENIERÍA BIOQUÍMICA', 'INGENIERÍA BIOQUÍMICA'),
        ('INGENIERÍA CIVIL', 'INGENIERÍA CIVIL'),
        ('INGENIERÍA ELECTROMECÁNICA', 'INGENIERÍA ELECTROMECÁNICA'),
        ('INGENIERÍA EN GESTIÓN EMPRESARIAL', 'INGENIERÍA EN GESTIÓN EMPRESARIAL'),
        ('INGENIERÍA DE SISTEMAS COMPUTACIONALES', 'INGENIERÍA DE SISTEMAS COMPUTACIONALES'),
        ('INGENIERÍA INDUSTRIAL', 'INGENIERÍA INDUSTRIAL'),
        ('INGENIERÍA INFORMÁTICA', 'INGENIERÍA INFORMÁTICA'),
        ('INGENIERÍA MECATRÓNICA', 'INGENIERÍA MECATRÓNICA'),
        ('INGENIERÍA QUÍMICA', 'INGENIERÍA QUÍMICA'),
        ('LICENCIATURA EN INFORMÁTICA', 'LICENCIATURA EN INFORMÁTICA'),
        ],default='INGENIERÍA BIOQUÍMICA')
    opcion_de_titulacion = models.CharField(
        max_length=150, choices=[
        ('Residencia Profesional', 'Residencia Profesional'),
        ('Proyecto de Investigación y/o Desarrollo Tecnológico', 'Proyecto de Investigación y/o Desarrollo Tecnológico'),
        ('Proyecto Integrador','Proyecto Integrador'),
        ('Proyecto Productivo','Proyecto Productivo'),
        ('Proyecto de Innovación Tecnológica','Proyecto de Innovación Tecnológica'),
        ('Proyecto de Emprededurismo','Proyecto de Emprededurismo'),
        ('Estancia','Estancia'),
        ('Tesis o  Tesina', 'Tesis o Tesina'),
        ('Examen General de Egreso de Licenciatura (EGEL) del Centro Nacional de Evaluación para la Educación Superior, A.C(CENEVAL)','Examen General de Egreso de Licenciatura (EGEL) del Centro Nacional de Evaluación para la Educación Superior, A.C(CENEVAL)'),
        ],default='Residencia Profesional') 
    nombre_del_asesor = models.CharField(
        max_length=100, choices=[
        ('ING. América Jiménez Damián', 'ING. América Jiménez Damián'),
        ('MTI. Ángel José Ortiz Loyo', 'MTI. Ángel José Ortiz Loyo'),
        ('ING. Abner Montenegro Hipólito', 'ING. Abner Montenegro Hipólito'),
        ('MTI. Abraham Alor De Los Santos', 'MTI. Abraham Alor De Los Santos'),
        ('ING. Alberta Huerta González', 'ING. Alberta Huerta González'),
        ('MTI. Aldo Rojas Cessa', 'ING. Alberta Huerta González'),
        ('DR. Alejandro Gregorio Nila Méndez', 'ING. Alberta Huerta González'),
        ('Lic. Alma Rosa Flores Doroteo', 'Lic. Alma Rosa Flores Doroteo'),
        ('MRT. Antelma Olivera Solorzano', 'MRT. Antelma Olivera Solorzano'),
        ('ING. Armando Hernández Montero', 'ING. Armando Hernández Montero'),
        ('ING. Aurora Medina Torres', 'ING. Aurora Medina Torres'),
        ('MMER. Beatriz Aparicio Candelario','MMER. Beatriz Aparicio Candelario'),
        ('ING. Carlos Ignacio Aguirre Domínguez','ING. Carlos Ignacio Aguirre Domínguez'),
        ('MITE. Carlos Romeo Posadas Trejo','MITE. Carlos Romeo Posadas Trejo'),
        ('LIC. César Augusto Gómez Vivero','LIC. César Augusto Gómez Vivero'),
        ('DR. Cid Ramón González González','DR. Cid Ramón González González'),
        ('MITE. Claudia Anahí Arias Salinas','MITE. Claudia Anahí Arias Salinas'),
        ('DOC. Claudia Lorena Valenzuela Aguilar','DOC. Claudia Lorena Valenzuela Aguilar'),
        ('MIA. Claudio Rosas Pérez','MIA. Claudio Rosas Pérez'),
        ('ING. Cruz Palacios Gerónimo','ING. Cruz Palacios Gerónimo'),
        ('MIC. Dante Javier Franyutti Limón','MIC. Dante Javier Franyutti Limón'),
        ('ING. Diana Martínez Ríos','ING. Diana Martínez Ríos'),
        ('MTI. Edwin Alberto Rodríguez Landero','MTI. Edwin Alberto Rodríguez Landero'),
        ('DRA. Elizabeta Hernández Domínguez','DRA. Elizabeta Hernández Domínguez'),
        ('LC. Elizabeth Pérez Cárdenas','LC. Elizabeth Pérez Cárdenas'),
        ('MTDRS. Elsa Beatriz González Licona','MTDRS. Elsa Beatriz González Licona'),
        ('ING. Erick Benjamín Arriola López','ING. Erick Benjamín Arriola López'),
        ('ING. Erika del Carmen Reyes Gómez','ING. Erika del Carmen Reyes Gómez'),
        ('MAGE. Erika Gómez Santos','MAGE. Erika Gómez Santos'),
        ('LIC. Evelia Mireya Ruiz Jara','LIC. Evelia Mireya Ruiz Jara'),
        ('ARQ. Fabiola Rojas Cessa','ARQ. Fabiola Rojas Cessa'),
        ('ARQ. Federico Alberto Orozco Garduza','ARQ. Federico Alberto Orozco Garduza'),
        ('MTI. Feliciano Sánchez Mendoza','MTI. Feliciano Sánchez Mendoza'),
        ('LC. Flora Gutiérrez Reyes','LC. Flora Gutiérrez Reyes'),
        ('MCCT. Francisco Gibrán García Candelario','MCCT. Francisco Gibrán García Candelario'),
        ('DR. Francisco Javier Gabino Román','DR. Francisco Javier Gabino Román'),
        ('MCDE. Francisco Manuel Lorenzo Hernández','MCDE. Francisco Manuel Lorenzo Hernández'),
        ('MITE. Gerardo Paxtián Méndez','MITE. Gerardo Paxtián Méndez'),
        ('MITE. Guiedani Zavala Orozco','MITE. Guiedani Zavala Orozco'),
        ('ING. Guillermo Santiago González','ING. Guillermo Santiago González'),
        ('ING. Gumer Ángel Antonio Olivera','ING. Gumer Ángel Antonio Olivera'),
        ('MCE. Gustavo Ramírez Viveros','MCE. Gustavo Ramírez Viveros'),
        ('MTI. Henry Izquierdo Ramírez','MTI. Henry Izquierdo Ramírez'),
        ('MTI. Isabel Cristina Arias Salinas','MTI. Isabel Cristina Arias Salinas'),
        ('ING. Isauro Arzola Temix','ING. Isauro Arzola Temix'),
        ('LD. Iván Aguirre Limón','LD. Iván Aguirre Limón'),
        ('ING. Iván Cristóbal Hernández Ramírez','ING. Iván Cristóbal Hernández Ramírez'),
        ('ING. Jaime Armando Morales Silva','ING. Jaime Armando Morales Silva'),
        ('IBQ. Janet del Carmen Alfonso Gómez','IBQ. Janet del Carmen Alfonso Gómez'),
        ('MAN. Jazmín Del Rocío Fonseca Domínguez','MAN. Jazmín Del Rocío Fonseca Domínguez'),
        ('DOC. Jesús Fernando Cruz Álvarez','DOC. Jesús Fernando Cruz Álvarez'),
        ('MTI. Jesús Hernández Mundo','MTI. Jesús Hernández Mundo'),
        ('LI. Jocelyn Ivette García Aquino','LI. Jocelyn Ivette García Aquino'),
        ('MITE. Jorge Aguilar Sixto','MITE. Jorge Aguilar Sixto'),
        ('MITE. Jorge Alberto Rojas Carranza','MITE. Jorge Alberto Rojas Carranza'),
        ('LI. José Alberto Domínguez Sandoval','LI. José Alberto Domínguez Sandoval'),
        ('BIOL. José Antonio González Rodríguez','BIOL. José Antonio González Rodríguez'),
        ('MITE. José Antonio Limón Cortaza','MITE. José Antonio Limón Cortaza'),            
        ('MTE. José Aurelio Ramírez González','MTE. José Aurelio Ramírez González'),
        ('ING. José Guadalupe Canela Morales','ING. José Guadalupe Canela Morales'),
        ('MITE. José Guadalupe Jerez Fidencio','MITE. José Guadalupe Jerez Fidencio'),
        ('MTI. José Hernández Rodríguez','MTI. José Hernández Rodríguez'),
        ('LIC. José Luis Rodríguez Gómez','LIC. José Luis Rodríguez Gómez'),
        ('MAGO. José Manuel Domínguez Campos','MAGO. José Manuel Domínguez Campos'),
        ('LIC. José Moguel Muñoz','LIC. José Moguel Muñoz'),
        ('DR. José Ramón Baca González','DR. José Ramón Baca González'),
        ('LIC. Josué Salgado Antonio','LIC. Josué Salgado Antonio'),
        ('LC. Juan Anastacio Silverio','LC. Juan Anastacio Silverio'),
        ('MITE. Juan Gabino Alemán López','MITE. Juan Gabino Alemán López'),
        ('LAE. Juan José Gómez Guzmán','LAE. Juan José Gómez Guzmán'),
        ('MDIS. Juan José San Juan Garduza','MDIS. Juan José San Juan Garduza'),
        ('ING. Juan José Tun Mendoza','ING. Juan José Tun Mendoza'),
        ('MIA. Juan Manuel Hernández Espíndola','MIA. Juan Manuel Hernández Espíndola'),
        ('MITE. Juan Velázquez Aguirre','MITE. Juan Velázquez Aguirre'),
        ('MGC. Judith Concepción Reyes Torres','MGC. Judith Concepción Reyes Torres'),
        ('ING. Julio Cesar Ortiz Antonio','ING. Julio Cesar Ortiz Antonio'),
        ('DRA. Karla Yasmín Ruiz Santos','DRA. Karla Yasmín Ruiz Santos'),
        ('LAET. Laura Luz Malpica Cano','LAET. Laura Luz Malpica Cano'),
        ('DRA. Leticia Carballo Perea','DRA. Leticia Carballo Perea'),
        ('ING. Leydi Yanet Hernández Quino','ING. Leydi Yanet Hernández Quino'),
        ('MITE. Lizbeth Ortiz Ovando','MITE. Lizbeth Ortiz Ovando'),
        ('LIC. Lizeth Vázquez Saturnino','LIC. Lizeth Vázquez Saturnino'),
        ('LAE. Lorenzo Gonzalez Pablo','LAE. Lorenzo Gonzalez Pablo'),
        ('MTI. Lucia del Carmen Ugarte Sánchez','MTI. Lucia del Carmen Ugarte Sánchez'),
        ('ING. Lucio Gutiérrez Reyes','ING. Lucio Gutiérrez Reyes'),
        ('MRH. Luz Del Carmen Aspiri Gutiérrez','MRH. Luz Del Carmen Aspiri Gutiérrez'),
        ('LI. Marbella Pineda Vega','LI. Marbella Pineda Vega'),
        ('ING. Marcos Ramírez Crisantos','ING. Marcos Ramírez Crisantos'),
        ('LIC. María del Pilar Gómez Uscanga','LIC. María del Pilar Gómez Uscanga'),
        ('LP. María Isabel Martínez Velázquez','LP. María Isabel Martínez Velázquez'),
        ('LC. María Luisa Rosaldo Izquierdo','LC. María Luisa Rosaldo Izquierdo'),
        ('LAET. Mariangela Aldana Mendoza','LAET. Mariangela Aldana Mendoza'),
        ('MDRS. Marisa Cocom Hipólito','MDRS. Marisa Cocom Hipólito'),
        ('LAE. Marisela López Padua','LAE. Marisela López Padua'),
        ('MII. Martha María Carrillo Ramírez','MII. Martha María Carrillo Ramírez'),
        ('LIC. Melba Márquez Prudencio','LIC. Melba Márquez Prudencio'),
        ('MTI. Miguel Ángel Rodríguez Mora','MTI. Miguel Ángel Rodríguez Mora'),
        ('MCE. Napoleón Santos Aguilera','MCE. Napoleón Santos Aguilera'),
        ('MTI. Natividad Juárez González','MTI. Natividad Juárez González'),
        ('LD. Noemi Genoveva Aguirre Guzmán','LD. Noemi Genoveva Aguirre Guzmán'),
        ('MTI. Pamela Lizette Guadalupe Cerdán Valdés','MTI. Pamela Lizette Guadalupe Cerdán Valdés'),
        ('LP. Raquel Romero Lara','LP. Raquel Romero Lara'),
        ('MTI. Rasomel Izquierdo Cruz','MTI. Rasomel Izquierdo Cruz'),
        ('DR. Ray Alfredo González Cancino','DR. Ray Alfredo González Cancino'),
        ('ING. Ricardo Macedonio Milagro','ING. Ricardo Macedonio Milagro'),
        ('LAE. Sandra Antonia Reyes Gutiérrez','LAE. Sandra Antonia Reyes Gutiérrez'),
        ('LIC. Serafín Hernández Aguilar','LIC. Serafín Hernández Aguilar'),
        ('MTI. Ulises Girón Jiménez','MTI. Ulises Girón Jiménez'),
        ('ISC. Vianey Fuentes Mateos','ISC. Vianey Fuentes Mateos'),
        ('ING. Víctor Gerónimo Martínez','ING. Víctor Gerónimo Martínez'),
        ('MITE. Victoria Castillo Miguel','MITE. Victoria Castillo Miguel'),
        ('MCA. Yolanda Retama Ortiz','MCA. Yolanda Retama Ortiz'),
        ('MADE. Yuridia Carrasco Domínguez','MADE. Yuridia Carrasco Domínguez'),
        ('ING. Juárez Robles Hugo Armando','ING. Juárez Robles Hugo Armando'),
        ('ING. Lino Salas Baeza','ING. Lino Salas Baeza'),
        ('LI. Darinel Antonio Librado','LI. Darinel Antonio Librado'),
        ('ING. Katya Nahayiba Olguin Martínez','ING. Katya Nahayiba Olguin Martínez'),
        ('ING. Jair Reyes Blanco','ING. Jair Reyes Blanco'),
        ('ING. Erick Alejandro Ramírez Martínez','ING. Erick Alejandro Ramírez Martínez'),
        ('MCIQ. Daniel Montalvo Salinas','MCIQ. Daniel Montalvo Salinas'),
        ('ING. Leydi Jazmín Reyes Mateo','ING. Leydi Jazmín Reyes Mateo'),
        ('MTDRS. Elsa Beatriz González Licona','MTDRS. Elsa Beatriz González Licona'),
        ('IBQ. Sugey Guillén Vergara','IBQ. Sugey Guillén Vergara'),
        ('ING. Marveli Juan Cruz','ING. Marveli Juan Cruz'),
        ('ING. Carlos Alberto Tun Culebro','ING. Carlos Alberto Tun Culebro'),
        ('MCIB. Rosa Isela Castillo Zamudio','MCIB. Rosa Isela Castillo Zamudio'),
        ], default='ING. América Jiménez Damián') 
    nombre_del_revisor_1 = models.CharField(
        max_length=100, choices=[
        ('ING. América Jiménez Damián', 'ING. América Jiménez Damián'),
        ('MTI. Ángel José Ortiz Loyo', 'MTI. Ángel José Ortiz Loyo'),
        ('ING. Abner Montenegro Hipólito', 'ING. Abner Montenegro Hipólito'),
        ('MTI. Abraham Alor De Los Santos', 'MTI. Abraham Alor De Los Santos'),
        ('ING. Alberta Huerta González', 'ING. Alberta Huerta González'),
        ('MTI. Aldo Rojas Cessa', 'ING. Alberta Huerta González'),
        ('DR. Alejandro Gregorio Nila Méndez', 'ING. Alberta Huerta González'),
        ('Lic. Alma Rosa Flores Doroteo', 'Lic. Alma Rosa Flores Doroteo'),
        ('MRT. Antelma Olivera Solorzano', 'MRT. Antelma Olivera Solorzano'),
        ('ING. Armando Hernández Montero', 'ING. Armando Hernández Montero'),
        ('ING. Aurora Medina Torres', 'ING. Aurora Medina Torres'),
        ('MMER. Beatriz Aparicio Candelario','MMER. Beatriz Aparicio Candelario'),
        ('ING. Carlos Ignacio Aguirre Domínguez','ING. Carlos Ignacio Aguirre Domínguez'),
        ('MITE. Carlos Romeo Posadas Trejo','MITE. Carlos Romeo Posadas Trejo'),
        ('LIC. César Augusto Gómez Vivero','LIC. César Augusto Gómez Vivero'),
        ('DR. Cid Ramón González González','DR. Cid Ramón González González'),
        ('MITE. Claudia Anahí Arias Salinas','MITE. Claudia Anahí Arias Salinas'),
        ('DOC. Claudia Lorena Valenzuela Aguilar','DOC. Claudia Lorena Valenzuela Aguilar'),
        ('MIA. Claudio Rosas Pérez','MIA. Claudio Rosas Pérez'),
        ('ING. Cruz Palacios Gerónimo','ING. Cruz Palacios Gerónimo'),
        ('MIC. Dante Javier Franyutti Limón','MIC. Dante Javier Franyutti Limón'),
        ('ING. Diana Martínez Ríos','ING. Diana Martínez Ríos'),
        ('MTI. Edwin Alberto Rodríguez Landero','MTI. Edwin Alberto Rodríguez Landero'),
        ('DRA. Elizabeta Hernández Domínguez','DRA. Elizabeta Hernández Domínguez'),
        ('LC. Elizabeth Pérez Cárdenas','LC. Elizabeth Pérez Cárdenas'),
        ('MTDRS. Elsa Beatriz González Licona','MTDRS. Elsa Beatriz González Licona'),
        ('ING. Erick Benjamín Arriola López','ING. Erick Benjamín Arriola López'),
        ('ING. Erika del Carmen Reyes Gómez','ING. Erika del Carmen Reyes Gómez'),
        ('MAGE. Erika Gómez Santos','MAGE. Erika Gómez Santos'),
        ('LIC. Evelia Mireya Ruiz Jara','LIC. Evelia Mireya Ruiz Jara'),
        ('ARQ. Fabiola Rojas Cessa','ARQ. Fabiola Rojas Cessa'),
        ('ARQ. Federico Alberto Orozco Garduza','ARQ. Federico Alberto Orozco Garduza'),
        ('MTI. Feliciano Sánchez Mendoza','MTI. Feliciano Sánchez Mendoza'),
        ('LC. Flora Gutiérrez Reyes','LC. Flora Gutiérrez Reyes'),
        ('MCCT. Francisco Gibrán García Candelario','MCCT. Francisco Gibrán García Candelario'),
        ('DR. Francisco Javier Gabino Román','DR. Francisco Javier Gabino Román'),
        ('MCDE. Francisco Manuel Lorenzo Hernández','MCDE. Francisco Manuel Lorenzo Hernández'),
        ('MITE. Gerardo Paxtián Méndez','MITE. Gerardo Paxtián Méndez'),
        ('MITE. Guiedani Zavala Orozco','MITE. Guiedani Zavala Orozco'),
        ('ING. Guillermo Santiago González','ING. Guillermo Santiago González'),
        ('ING. Gumer Ángel Antonio Olivera','ING. Gumer Ángel Antonio Olivera'),
        ('MCE. Gustavo Ramírez Viveros','MCE. Gustavo Ramírez Viveros'),
        ('MTI. Henry Izquierdo Ramírez','MTI. Henry Izquierdo Ramírez'),
        ('MTI. Isabel Cristina Arias Salinas','MTI. Isabel Cristina Arias Salinas'),
        ('ING. Isauro Arzola Temix','ING. Isauro Arzola Temix'),
        ('LD. Iván Aguirre Limón','LD. Iván Aguirre Limón'),
        ('ING. Iván Cristóbal Hernández Ramírez','ING. Iván Cristóbal Hernández Ramírez'),
        ('ING. Jaime Armando Morales Silva','ING. Jaime Armando Morales Silva'),
        ('IBQ. Janet del Carmen Alfonso Gómez','IBQ. Janet del Carmen Alfonso Gómez'),
        ('MAN. Jazmín Del Rocío Fonseca Domínguez','MAN. Jazmín Del Rocío Fonseca Domínguez'),
        ('DOC. Jesús Fernando Cruz Álvarez','DOC. Jesús Fernando Cruz Álvarez'),
        ('MTI. Jesús Hernández Mundo','MTI. Jesús Hernández Mundo'),
        ('LI. Jocelyn Ivette García Aquino','LI. Jocelyn Ivette García Aquino'),
        ('MITE. Jorge Aguilar Sixto','MITE. Jorge Aguilar Sixto'),
        ('MITE. Jorge Alberto Rojas Carranza','MITE. Jorge Alberto Rojas Carranza'),
        ('LI. José Alberto Domínguez Sandoval','LI. José Alberto Domínguez Sandoval'),
        ('BIOL. José Antonio González Rodríguez','BIOL. José Antonio González Rodríguez'),
        ('MITE. José Antonio Limón Cortaza','MITE. José Antonio Limón Cortaza'),            
        ('MTE. José Aurelio Ramírez González','MTE. José Aurelio Ramírez González'),
        ('ING. José Guadalupe Canela Morales','ING. José Guadalupe Canela Morales'),
        ('MITE. José Guadalupe Jerez Fidencio','MITE. José Guadalupe Jerez Fidencio'),
        ('MTI. José Hernández Rodríguez','MTI. José Hernández Rodríguez'),
        ('LIC. José Luis Rodríguez Gómez','LIC. José Luis Rodríguez Gómez'),
        ('MAGO. José Manuel Domínguez Campos','MAGO. José Manuel Domínguez Campos'),
        ('LIC. José Moguel Muñoz','LIC. José Moguel Muñoz'),
        ('DR. José Ramón Baca González','DR. José Ramón Baca González'),
        ('LIC. Josué Salgado Antonio','LIC. Josué Salgado Antonio'),
        ('LC. Juan Anastacio Silverio','LC. Juan Anastacio Silverio'),
        ('MITE. Juan Gabino Alemán López','MITE. Juan Gabino Alemán López'),
        ('LAE. Juan José Gómez Guzmán','LAE. Juan José Gómez Guzmán'),
        ('MDIS. Juan José San Juan Garduza','MDIS. Juan José San Juan Garduza'),
        ('ING. Juan José Tun Mendoza','ING. Juan José Tun Mendoza'),
        ('MIA. Juan Manuel Hernández Espíndola','MIA. Juan Manuel Hernández Espíndola'),
        ('MITE. Juan Velázquez Aguirre','MITE. Juan Velázquez Aguirre'),
        ('MGC. Judith Concepción Reyes Torres','MGC. Judith Concepción Reyes Torres'),
        ('ING. Julio Cesar Ortiz Antonio','ING. Julio Cesar Ortiz Antonio'),
        ('DRA. Karla Yasmín Ruiz Santos','DRA. Karla Yasmín Ruiz Santos'),
        ('LAET. Laura Luz Malpica Cano','LAET. Laura Luz Malpica Cano'),
        ('DRA. Leticia Carballo Perea','DRA. Leticia Carballo Perea'),
        ('ING. Leydi Yanet Hernández Quino','ING. Leydi Yanet Hernández Quino'),
        ('MITE. Lizbeth Ortiz Ovando','MITE. Lizbeth Ortiz Ovando'),
        ('LIC. Lizeth Vázquez Saturnino','LIC. Lizeth Vázquez Saturnino'),
        ('LAE. Lorenzo Gonzalez Pablo','LAE. Lorenzo Gonzalez Pablo'),
        ('MTI. Lucia del Carmen Ugarte Sánchez','MTI. Lucia del Carmen Ugarte Sánchez'),
        ('ING. Lucio Gutiérrez Reyes','ING. Lucio Gutiérrez Reyes'),
        ('MRH. Luz Del Carmen Aspiri Gutiérrez','MRH. Luz Del Carmen Aspiri Gutiérrez'),
        ('LI. Marbella Pineda Vega','LI. Marbella Pineda Vega'),
        ('ING. Marcos Ramírez Crisantos','ING. Marcos Ramírez Crisantos'),
        ('LIC. María del Pilar Gómez Uscanga','LIC. María del Pilar Gómez Uscanga'),
        ('LP. María Isabel Martínez Velázquez','LP. María Isabel Martínez Velázquez'),
        ('LC. María Luisa Rosaldo Izquierdo','LC. María Luisa Rosaldo Izquierdo'),
        ('LAET. Mariangela Aldana Mendoza','LAET. Mariangela Aldana Mendoza'),
        ('MDRS. Marisa Cocom Hipólito','MDRS. Marisa Cocom Hipólito'),
        ('LAE. Marisela López Padua','LAE. Marisela López Padua'),
        ('MII. Martha María Carrillo Ramírez','MII. Martha María Carrillo Ramírez'),
        ('LIC. Melba Márquez Prudencio','LIC. Melba Márquez Prudencio'),
        ('MTI. Miguel Ángel Rodríguez Mora','MTI. Miguel Ángel Rodríguez Mora'),
        ('MCE. Napoleón Santos Aguilera','MCE. Napoleón Santos Aguilera'),
        ('MTI. Natividad Juárez González','MTI. Natividad Juárez González'),
        ('LD. Noemi Genoveva Aguirre Guzmán','LD. Noemi Genoveva Aguirre Guzmán'),
        ('MTI. Pamela Lizette Guadalupe Cerdán Valdés','MTI. Pamela Lizette Guadalupe Cerdán Valdés'),
        ('LP. Raquel Romero Lara','LP. Raquel Romero Lara'),
        ('MTI. Rasomel Izquierdo Cruz','MTI. Rasomel Izquierdo Cruz'),
        ('DR. Ray Alfredo González Cancino','DR. Ray Alfredo González Cancino'),
        ('ING. Ricardo Macedonio Milagro','ING. Ricardo Macedonio Milagro'),
        ('LAE. Sandra Antonia Reyes Gutiérrez','LAE. Sandra Antonia Reyes Gutiérrez'),
        ('LIC. Serafín Hernández Aguilar','LIC. Serafín Hernández Aguilar'),
        ('MTI. Ulises Girón Jiménez','MTI. Ulises Girón Jiménez'),
        ('ISC. Vianey Fuentes Mateos','ISC. Vianey Fuentes Mateos'),
        ('ING. Víctor Gerónimo Martínez','ING. Víctor Gerónimo Martínez'),
        ('MITE. Victoria Castillo Miguel','MITE. Victoria Castillo Miguel'),
        ('MCA. Yolanda Retama Ortiz','MCA. Yolanda Retama Ortiz'),
        ('MADE. Yuridia Carrasco Domínguez','MADE. Yuridia Carrasco Domínguez'),
        ('ING. Juárez Robles Hugo Armando','ING. Juárez Robles Hugo Armando'),
        ('ING. Lino Salas Baeza','ING. Lino Salas Baeza'),
        ('LI. Darinel Antonio Librado','LI. Darinel Antonio Librado'),
        ('ING. Katya Nahayiba Olguin Martínez','ING. Katya Nahayiba Olguin Martínez'),
        ('ING. Jair Reyes Blanco','ING. Jair Reyes Blanco'),
        ('ING. Erick Alejandro Ramírez Martínez','ING. Erick Alejandro Ramírez Martínez'),
        ('MCIQ. Daniel Montalvo Salinas','MCIQ. Daniel Montalvo Salinas'),
        ('ING. Leydi Jazmín Reyes Mateo','ING. Leydi Jazmín Reyes Mateo'),
        ('MTDRS. Elsa Beatriz González Licona','MTDRS. Elsa Beatriz González Licona'),
        ('IBQ. Sugey Guillén Vergara','IBQ. Sugey Guillén Vergara'),
        ('ING. Marveli Juan Cruz','ING. Marveli Juan Cruz'),
        ('ING. Carlos Alberto Tun Culebro','ING. Carlos Alberto Tun Culebro'),
        ('MCIB. Rosa Isela Castillo Zamudio','MCIB. Rosa Isela Castillo Zamudio'),
        ], default='ING. América Jiménez Damián')
    
    nombre_del_revisor_2 = models.CharField(
        max_length=100, choices=[
        ('ING. América Jiménez Damián', 'ING. América Jiménez Damián'),
        ('MTI. Ángel José Ortiz Loyo', 'MTI. Ángel José Ortiz Loyo'),
        ('ING. Abner Montenegro Hipólito', 'ING. Abner Montenegro Hipólito'),
        ('MTI. Abraham Alor De Los Santos', 'MTI. Abraham Alor De Los Santos'),
        ('ING. Alberta Huerta González', 'ING. Alberta Huerta González'),
        ('MTI. Aldo Rojas Cessa', 'ING. Alberta Huerta González'),
        ('DR. Alejandro Gregorio Nila Méndez', 'ING. Alberta Huerta González'),
        ('Lic. Alma Rosa Flores Doroteo', 'Lic. Alma Rosa Flores Doroteo'),
        ('MRT. Antelma Olivera Solorzano', 'MRT. Antelma Olivera Solorzano'),
        ('ING. Armando Hernández Montero', 'ING. Armando Hernández Montero'),
        ('ING. Aurora Medina Torres', 'ING. Aurora Medina Torres'),
        ('MMER. Beatriz Aparicio Candelario','MMER. Beatriz Aparicio Candelario'),
        ('ING. Carlos Ignacio Aguirre Domínguez','ING. Carlos Ignacio Aguirre Domínguez'),
        ('MITE. Carlos Romeo Posadas Trejo','MITE. Carlos Romeo Posadas Trejo'),
        ('LIC. César Augusto Gómez Vivero','LIC. César Augusto Gómez Vivero'),
        ('DR. Cid Ramón González González','DR. Cid Ramón González González'),
        ('MITE. Claudia Anahí Arias Salinas','MITE. Claudia Anahí Arias Salinas'),
        ('DOC. Claudia Lorena Valenzuela Aguilar','DOC. Claudia Lorena Valenzuela Aguilar'),
        ('MIA. Claudio Rosas Pérez','MIA. Claudio Rosas Pérez'),
        ('ING. Cruz Palacios Gerónimo','ING. Cruz Palacios Gerónimo'),
        ('MIC. Dante Javier Franyutti Limón','MIC. Dante Javier Franyutti Limón'),
        ('ING. Diana Martínez Ríos','ING. Diana Martínez Ríos'),
        ('MTI. Edwin Alberto Rodríguez Landero','MTI. Edwin Alberto Rodríguez Landero'),
        ('DRA. Elizabeta Hernández Domínguez','DRA. Elizabeta Hernández Domínguez'),
        ('LC. Elizabeth Pérez Cárdenas','LC. Elizabeth Pérez Cárdenas'),
        ('MTDRS. Elsa Beatriz González Licona','MTDRS. Elsa Beatriz González Licona'),
        ('ING. Erick Benjamín Arriola López','ING. Erick Benjamín Arriola López'),
        ('ING. Erika del Carmen Reyes Gómez','ING. Erika del Carmen Reyes Gómez'),
        ('MAGE. Erika Gómez Santos','MAGE. Erika Gómez Santos'),
        ('LIC. Evelia Mireya Ruiz Jara','LIC. Evelia Mireya Ruiz Jara'),
        ('ARQ. Fabiola Rojas Cessa','ARQ. Fabiola Rojas Cessa'),
        ('ARQ. Federico Alberto Orozco Garduza','ARQ. Federico Alberto Orozco Garduza'),
        ('MTI. Feliciano Sánchez Mendoza','MTI. Feliciano Sánchez Mendoza'),
        ('LC. Flora Gutiérrez Reyes','LC. Flora Gutiérrez Reyes'),
        ('MCCT. Francisco Gibrán García Candelario','MCCT. Francisco Gibrán García Candelario'),
        ('DR. Francisco Javier Gabino Román','DR. Francisco Javier Gabino Román'),
        ('MCDE. Francisco Manuel Lorenzo Hernández','MCDE. Francisco Manuel Lorenzo Hernández'),
        ('MITE. Gerardo Paxtián Méndez','MITE. Gerardo Paxtián Méndez'),
        ('MITE. Guiedani Zavala Orozco','MITE. Guiedani Zavala Orozco'),
        ('ING. Guillermo Santiago González','ING. Guillermo Santiago González'),
        ('ING. Gumer Ángel Antonio Olivera','ING. Gumer Ángel Antonio Olivera'),
        ('MCE. Gustavo Ramírez Viveros','MCE. Gustavo Ramírez Viveros'),
        ('MTI. Henry Izquierdo Ramírez','MTI. Henry Izquierdo Ramírez'),
        ('MTI. Isabel Cristina Arias Salinas','MTI. Isabel Cristina Arias Salinas'),
        ('ING. Isauro Arzola Temix','ING. Isauro Arzola Temix'),
        ('LD. Iván Aguirre Limón','LD. Iván Aguirre Limón'),
        ('ING. Iván Cristóbal Hernández Ramírez','ING. Iván Cristóbal Hernández Ramírez'),
        ('ING. Jaime Armando Morales Silva','ING. Jaime Armando Morales Silva'),
        ('IBQ. Janet del Carmen Alfonso Gómez','IBQ. Janet del Carmen Alfonso Gómez'),
        ('MAN. Jazmín Del Rocío Fonseca Domínguez','MAN. Jazmín Del Rocío Fonseca Domínguez'),
        ('DOC. Jesús Fernando Cruz Álvarez','DOC. Jesús Fernando Cruz Álvarez'),
        ('MTI. Jesús Hernández Mundo','MTI. Jesús Hernández Mundo'),
        ('LI. Jocelyn Ivette García Aquino','LI. Jocelyn Ivette García Aquino'),
        ('MITE. Jorge Aguilar Sixto','MITE. Jorge Aguilar Sixto'),
        ('MITE. Jorge Alberto Rojas Carranza','MITE. Jorge Alberto Rojas Carranza'),
        ('LI. José Alberto Domínguez Sandoval','LI. José Alberto Domínguez Sandoval'),
        ('BIOL. José Antonio González Rodríguez','BIOL. José Antonio González Rodríguez'),
        ('MITE. José Antonio Limón Cortaza','MITE. José Antonio Limón Cortaza'),            
        ('MTE. José Aurelio Ramírez González','MTE. José Aurelio Ramírez González'),
        ('ING. José Guadalupe Canela Morales','ING. José Guadalupe Canela Morales'),
        ('MITE. José Guadalupe Jerez Fidencio','MITE. José Guadalupe Jerez Fidencio'),
        ('MTI. José Hernández Rodríguez','MTI. José Hernández Rodríguez'),
        ('LIC. José Luis Rodríguez Gómez','LIC. José Luis Rodríguez Gómez'),
        ('MAGO. José Manuel Domínguez Campos','MAGO. José Manuel Domínguez Campos'),
        ('LIC. José Moguel Muñoz','LIC. José Moguel Muñoz'),
        ('DR. José Ramón Baca González','DR. José Ramón Baca González'),
        ('LIC. Josué Salgado Antonio','LIC. Josué Salgado Antonio'),
        ('LC. Juan Anastacio Silverio','LC. Juan Anastacio Silverio'),
        ('MITE. Juan Gabino Alemán López','MITE. Juan Gabino Alemán López'),
        ('LAE. Juan José Gómez Guzmán','LAE. Juan José Gómez Guzmán'),
        ('MDIS. Juan José San Juan Garduza','MDIS. Juan José San Juan Garduza'),
        ('ING. Juan José Tun Mendoza','ING. Juan José Tun Mendoza'),
        ('MIA. Juan Manuel Hernández Espíndola','MIA. Juan Manuel Hernández Espíndola'),
        ('MITE. Juan Velázquez Aguirre','MITE. Juan Velázquez Aguirre'),
        ('MGC. Judith Concepción Reyes Torres','MGC. Judith Concepción Reyes Torres'),
        ('ING. Julio Cesar Ortiz Antonio','ING. Julio Cesar Ortiz Antonio'),
        ('DRA. Karla Yasmín Ruiz Santos','DRA. Karla Yasmín Ruiz Santos'),
        ('LAET. Laura Luz Malpica Cano','LAET. Laura Luz Malpica Cano'),
        ('DRA. Leticia Carballo Perea','DRA. Leticia Carballo Perea'),
        ('ING. Leydi Yanet Hernández Quino','ING. Leydi Yanet Hernández Quino'),
        ('MITE. Lizbeth Ortiz Ovando','MITE. Lizbeth Ortiz Ovando'),
        ('LIC. Lizeth Vázquez Saturnino','LIC. Lizeth Vázquez Saturnino'),
        ('LAE. Lorenzo Gonzalez Pablo','LAE. Lorenzo Gonzalez Pablo'),
        ('MTI. Lucia del Carmen Ugarte Sánchez','MTI. Lucia del Carmen Ugarte Sánchez'),
        ('ING. Lucio Gutiérrez Reyes','ING. Lucio Gutiérrez Reyes'),
        ('MRH. Luz Del Carmen Aspiri Gutiérrez','MRH. Luz Del Carmen Aspiri Gutiérrez'),
        ('LI. Marbella Pineda Vega','LI. Marbella Pineda Vega'),
        ('ING. Marcos Ramírez Crisantos','ING. Marcos Ramírez Crisantos'),
        ('LIC. María del Pilar Gómez Uscanga','LIC. María del Pilar Gómez Uscanga'),
        ('LP. María Isabel Martínez Velázquez','LP. María Isabel Martínez Velázquez'),
        ('LC. María Luisa Rosaldo Izquierdo','LC. María Luisa Rosaldo Izquierdo'),
        ('LAET. Mariangela Aldana Mendoza','LAET. Mariangela Aldana Mendoza'),
        ('MDRS. Marisa Cocom Hipólito','MDRS. Marisa Cocom Hipólito'),
        ('LAE. Marisela López Padua','LAE. Marisela López Padua'),
        ('MII. Martha María Carrillo Ramírez','MII. Martha María Carrillo Ramírez'),
        ('LIC. Melba Márquez Prudencio','LIC. Melba Márquez Prudencio'),
        ('MTI. Miguel Ángel Rodríguez Mora','MTI. Miguel Ángel Rodríguez Mora'),
        ('MCE. Napoleón Santos Aguilera','MCE. Napoleón Santos Aguilera'),
        ('MTI. Natividad Juárez González','MTI. Natividad Juárez González'),
        ('LD. Noemi Genoveva Aguirre Guzmán','LD. Noemi Genoveva Aguirre Guzmán'),
        ('MTI. Pamela Lizette Guadalupe Cerdán Valdés','MTI. Pamela Lizette Guadalupe Cerdán Valdés'),
        ('LP. Raquel Romero Lara','LP. Raquel Romero Lara'),
        ('MTI. Rasomel Izquierdo Cruz','MTI. Rasomel Izquierdo Cruz'),
        ('DR. Ray Alfredo González Cancino','DR. Ray Alfredo González Cancino'),
        ('ING. Ricardo Macedonio Milagro','ING. Ricardo Macedonio Milagro'),
        ('LAE. Sandra Antonia Reyes Gutiérrez','LAE. Sandra Antonia Reyes Gutiérrez'),
        ('LIC. Serafín Hernández Aguilar','LIC. Serafín Hernández Aguilar'),
        ('MTI. Ulises Girón Jiménez','MTI. Ulises Girón Jiménez'),
        ('ISC. Vianey Fuentes Mateos','ISC. Vianey Fuentes Mateos'),
        ('ING. Víctor Gerónimo Martínez','ING. Víctor Gerónimo Martínez'),
        ('MITE. Victoria Castillo Miguel','MITE. Victoria Castillo Miguel'),
        ('MCA. Yolanda Retama Ortiz','MCA. Yolanda Retama Ortiz'),
        ('MADE. Yuridia Carrasco Domínguez','MADE. Yuridia Carrasco Domínguez'),
        ('ING. Juárez Robles Hugo Armando','ING. Juárez Robles Hugo Armando'),
        ('ING. Lino Salas Baeza','ING. Lino Salas Baeza'),
        ('LI. Darinel Antonio Librado','LI. Darinel Antonio Librado'),
        ('ING. Katya Nahayiba Olguin Martínez','ING. Katya Nahayiba Olguin Martínez'),
        ('ING. Jair Reyes Blanco','ING. Jair Reyes Blanco'),
        ('ING. Erick Alejandro Ramírez Martínez','ING. Erick Alejandro Ramírez Martínez'),
        ('MCIQ. Daniel Montalvo Salinas','MCIQ. Daniel Montalvo Salinas'),
        ('ING. Leydi Jazmín Reyes Mateo','ING. Leydi Jazmín Reyes Mateo'),
        ('MTDRS. Elsa Beatriz González Licona','MTDRS. Elsa Beatriz González Licona'),
        ('IBQ. Sugey Guillén Vergara','IBQ. Sugey Guillén Vergara'),
        ('ING. Marveli Juan Cruz','ING. Marveli Juan Cruz'),
        ('ING. Carlos Alberto Tun Culebro','ING. Carlos Alberto Tun Culebro'),
        ('MCIB. Rosa Isela Castillo Zamudio','MCIB. Rosa Isela Castillo Zamudio'),
        ], default='ING. América Jiménez Damián')
    
    lugar = models.CharField(max_length=100, choices=[
        ('Acayucan', 'Acayucan'),
        ('Oluta', 'Oluta'),
        ('Jaltipan','Jaltipan'),
        ('Texistepec', 'Texistepec'),
        ('Cosoleacaque', 'Cosoleacaque'),
        ('Hueyapan','Hueyapan'),
        ('Covarrubias','Covarrubias'),
        ('Otro', 'Otro')
        ],default= 'Acayucan')
    discapacidad = models.CharField(max_length=100, choices=[
        ('Si', 'Si'),
        ('No', 'No')
        ],default='Si')
    genero = models.CharField(max_length=100, choices=[
        ('Hombre', 'Hombre'),
        ('Mujer', 'Mujer')
        ],default='Hombre')
    modalidad = models.CharField(max_length=100, choices=[
        ('Escolarizado', 'Escolarizado'),
        ('Sabatino', 'Sabatino'),
        ('Dominical','Dominical'),
        ('Extensión Hueyapan', 'Extensión Hueyapan'),
        ('Extensión Uxpanapan', 'Extensión Uxpanapan')
        ],default='Escolarizado')
    
        
    def __str__(self):
        return f"{self.correo} {self.matricula}{self.nombre} {self.carrera} {self.apellido_paterno} {self.nombre_del_proyecto} {self.apellido_materno}  {self.edad} {self.promedio} {self.opcion_de_titulacion} {self.nombre_del_asesor}{self.nombre_del_revisor_1}{self.nombre_del_revisor_2} {self.discapacidad} {self.genero} {self.modalidad} {self.dialecto} {self.telefono}"
    #Eliminar archivo
    def delete(self, *args, **kwargs):
        # Elimina el archivo cuando se borra el objeto
        if self.archivo:
            storage, path = self.archivo.storage, self.archivo.path
            storage.delete(path)
        super().delete(*args, **kwargs)
    
    
class Profesor (models.Model):
    sigla = models.CharField(max_length=10, default="")
    nombreProfesor = models.CharField(max_length=100)
    apellidoPaterno = models.CharField(max_length=100, default="")
    apellidoMaterno = models.CharField(max_length=100, default="")
    cedulaProfesor = models.IntegerField()
    
    def __str__(self):
        return f"{self.sigla} {self.nombreProfesor} {self.cedulaProfesor} {self.apellidoMaterno} {self.apellidoMaterno}"